indent-width = 4
extend-exclude = [".vscode", ".idea", "__pycache__", ".python-version", ".ruff.toml", "ruff.toml", "setup.cfg", "pyproject.toml", "*_test.py"]
line-length = 120
show-fixes = true

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
preview = true
skip-magic-trailing-comma = false
docstring-code-line-length = 100
line-ending = "lf"

[lint]
# D - Enable all `pydocstyle` rules, limiting to those that adhere to the Pep257 convention enabled via `convention = "pep257"` below
select = ["I", "D"]
ignore = [
    "D100",  # pydocstyle: Missing docstring in public module.
    "D101",  # pydocstyle: Missing docstring in public class.
    "D103",  # pydocstyle: Missing docstring in public function
    "D102",  # pydocstyle: Missing docstring in public method.
    "D104",  # pydocstyle: Missing docstring in public package.
    "D105",  # pydocstyle: Missing docstring in magic method (e.g., `__init__`).
    "D107",  # pydocstyle: Missing docstring in `__init__` method.
]

[lint.pydocstyle]
convention = "pep257"
